apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.secrets.api.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}    
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
  name: {{ .Values.secrets.api.name }}
data:
  api_keycloak_client_id: {{ .Values.secrets.api.api_keycloak_client_id | b64enc }}
  api_keycloak_client_secret: {{ .Values.secrets.api.api_keycloak_client_secret | b64enc }}  