apiVersion: v1
kind: Service
metadata:    
  labels:
    app.kubernetes.io/name: mongodb-executor
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
  name: mongodb-executor
spec:
  type: {{ .Values.services.mongodb_executor.type }}
  ports:
    - name: "mongo"
      port: {{ .Values.services.mongodb_executor.port }}
      targetPort: {{ .Values.services.mongodb_executor.port }}
      protocol: {{ .Values.services.mongodb_executor.protocol }}
  selector:
    app.kubernetes.io/name: mongodb-executor
status:
  loadBalancer: {}
