apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-executor-config
  labels:
    app.kubernetes.io/part-of: {{ .Chart.Name }}    
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
data:
  init-mongo.sh: |
    set -e

    mongo <<EOF
    use {{ .Values.secrets.mongodb_executor.mongodb_initdb }}

    db.createUser({
    user: '{{ .Values.secrets.mongodb_executor.mongodb_initdb_username }}',
    pwd: '{{ .Values.secrets.mongodb_executor.mongodb_initdb_password }}',
    roles: [{
        role: 'readWrite',
        db: '{{ .Values.secrets.mongodb_executor.mongodb_initdb }}'
    }]
    })

    db.createCollection('jobs');

    EOF