apiVersion: v1
kind: Service
metadata:  
  labels:
    app.kubernetes.io/name: {{ .Values.services.zookeeper.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
  name: {{ .Values.services.zookeeper.name }}
spec:
  type: {{ .Values.services.zookeeper.type }}
  ports:
    - name: "2181"
      port: {{ .Values.services.zookeeper.port }}
      targetPort: {{ .Values.services.zookeeper.port }}
      protocol: {{ .Values.services.zookeeper.protocol }}      
  selector:
    app.kubernetes.io/name: {{ .Values.services.zookeeper.name }}
status:
  loadBalancer: {}
