apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.route.api_app.name }}  
  labels:
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
spec:
  host: {{ .Values.services.api_app.name }}-{{ .Values.project.name }}.{{ .Values.project.domain }}
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ .Values.services.api_app.name }}
    weight: 100