apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmaps.api_app.name }}
  labels:
    app.kubernetes.io/part-of: {{ .Chart.Name }}    
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
data:  
  port: "{{ .Values.configmaps.api_app.port}}"
  keycloak_base_url: http://{{ .Values.services.keycloak.name }}-{{ .Values.project.name }}.{{ .Values.project.domain }}
  api_url_base: {{ .Values.services.api.name }}-{{ .Values.project.name }}.{{ .Values.project.domain }}
  api_endpoint: http://{{ .Values.services.api.name }}-{{ .Values.project.name }}.{{ .Values.project.domain }}/api