apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.yaml convert -c -o .
    kompose.service.expose: "true"
    kompose.service.type: LoadBalancer
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: injector
  name: injector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: injector
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../docker-compose.yaml convert -c -o .
        kompose.service.expose: "true"
        kompose.service.type: LoadBalancer
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: injector
    spec:
      containers:
        - env:
            - name: INJECTOR_CRON
            - name: INJECTOR_DB_HOST
            - name: INJECTOR_DB_NAME
            - name: INJECTOR_DB_PASSWORD
            - name: INJECTOR_DB_PORT
            - name: INJECTOR_DB_USER
            - name: INJECTOR_HTTP_PORT
            - name: INJECTOR_MEDIASTACK_APIKEY
            - name: INJECTOR_MEDIASTACK_URL
            - name: INJECTOR_NEWSAPI_APIKEY
            - name: INJECTOR_NEWSAPI_URL
            - name: INJECTOR_NEWSDATA_APIKEY
            - name: INJECTOR_NEWSDATA_URL
            - name: KAFKA_SERVERS
            - name: MINIO_ENDPOINT
            - name: MINIO_ROOT_PASSWORD
            - name: MINIO_ROOT_USER
            - name: REDIS_ENDPOINT
            - name: REDIS_PASSWORD
            - name: TZ
              value: Europe/Madrid
          image: marcelodsales/injector
          name: injector
          ports:
            - containerPort: 8080
          resources: {}
      hostname: injector
      restartPolicy: Always
status: {}
