apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.yaml convert -c -o .
    kompose.service.expose: "true"
    kompose.service.type: LoadBalancer
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api-app-tcp
  name: api-app-tcp
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: api-app
  type: LoadBalancer
status:
  loadBalancer: {}
