apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.yaml convert -c -o .
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: executor
  name: executor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: executor
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../docker-compose.yaml convert -c -o .
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: executor
    spec:
      containers:
        - env:
            - name: INJECTOR_ENDPOINT
            - name: KAFKA_SERVERS
            - name: MINIO_ENDPOINT
            - name: MINIO_ROOT_PASSWORD
            - name: MINIO_ROOT_USER
            - name: MONGODB_DB_NAME
            - name: MONGODB_DB_PASSWORD
            - name: MONGODB_DB_USER
            - name: MONGODB_URL
            - name: REDIS_ENDPOINT
            - name: REDIS_PASSWORD
            - name: TZ
              value: Europe/Madrid
          image: marcelodsales/executor
          name: executor
          ports:
            - containerPort: 8080
          resources: {}
      hostname: executor
      restartPolicy: Always
status: {}
