apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.secrets.mongodb_executor.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}    
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
  name: {{ .Values.secrets.mongodb_executor.name }}
data:
  mongodb_initdb: {{ .Values.secrets.mongodb_executor.mongodb_initdb | b64enc }}
  mongodb_initdb_password: {{ .Values.secrets.mongodb_executor.mongodb_initdb_password | b64enc }}
  mongodb_initdb_root_password: {{ .Values.secrets.mongodb_executor.mongodb_initdb_root_password | b64enc }}
  mongodb_initdb_root_username: {{ .Values.secrets.mongodb_executor.mongodb_initdb_root_username | b64enc }}
  mongodb_initdb_username: {{ .Values.secrets.mongodb_executor.mongodb_initdb_username | b64enc }}