apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:    
    app.kubernetes.io/name: postgres-keycloak
    app.kubernetes.io/part-of: {{ .Chart.Name }}    
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
    app.openshift.io/runtime: postgresql
    app.kubernetes.io/component: database
  name: postgres-keycloak
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-keycloak
  strategy:
    type: Recreate
  template:
    metadata:      
      labels:
        app.kubernetes.io/name: postgres-keycloak
    spec:
      containers:
        - env:
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.postgres_keycloak.name }}
                  key: postgres_db
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.postgres_keycloak.name }}
                  key: postgres_password
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.postgres_keycloak.name}}
                  key: postgres_user
            - name: TZ
              value: Europe/Madrid
          image: {{ .Values.images.postgres_keycloak.name}}:{{ .Values.images.postgres_keycloak.tag }}
          name: postgres-keycloak
          ports:
            - containerPort: {{ .Values.services.postgres_keycloak.port }}
          securityContext:
            capabilities: {}
            privileged: false
          resources:
            limits:
              memory: 512Mi
          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - '--live'
            initialDelaySeconds: 120
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: postgres-keycloak-data
      hostname: postgres-keycloak
      restartPolicy: Always
      volumes:
        - name: postgres-keycloak-data
          persistentVolumeClaim:
            claimName: postgres-keycloak-data
status: {}
