apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.secrets.postgres_injector.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}    
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
  name: {{ .Values.secrets.postgres_injector.name }}
data:
  postgres_db: {{ .Values.secrets.postgres_injector.postgres_db | b64enc }}
  postgres_user: {{ .Values.secrets.postgres_injector.postgres_user | b64enc }}
  postgres_password: {{ .Values.secrets.postgres_injector.postgres_password | b64enc }}