
# Images
images:  
  observer:
    name: marcelodsales/observer
    tag: latest
  injector:
    name: marcelodsales/injector
    tag: latest
  api:
    name: marcelodsales/api
    tag: latest

# Services
services:  
  injector:
    name: injector
    type: ClusterIP
    port: 8080
    protocol: TCP
  api:
    name: api
    type: LoadBalancer
    port: 8080
    protocol: TCP
  

# Secrets
secrets:  
  injector:
    name: injector-secret
    injector_newsdata_apikey: pub_146789360c2a1420986503a543273fbf22306
    injector_newsapi_apikey: 3911bdc960ab4abfb3efb9630ab25188
    injector_mediastack_apikey: 5d1a42a53fbaedc4e46d62157bec1f16

  api:
    name: api-secret
    api_keycloak_client_id: api-backend
    api_keycloak_client_secret: jIjvenRCzr0x0ccV6WDjDbh22NBluhPf
    
# ConfigMaps
configmaps:
  observer:
    name: observer-config
    observer_metrics_schedule: "30s"
  
  injector:
    name: injector-config
    injector_newsdata_url: https://newsdata.io/api/1
    injector_newsapi_url: https://newsapi.org/v2
    injector_mediastack_url: http://api.mediastack.com/v1
    injector_cron: "0 * * * * ?"

  api:
    name: api-config

ingress:
  api:
    name: api-ingress
    host: api