apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.yaml convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api-app
  name: api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../docker-compose.yaml convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: api-app
    spec:
      containers:
        - env:
            - name: API_ENDPOINT
              value: /api
            - name: API_URL_BASE
            - name: KEYCLOAK_BASE_URL
          image: marcelodsales/api-app
          name: api-app
          ports:
            - containerPort: 80
          resources: {}
      hostname: api-app
      restartPolicy: Always
status: {}
