apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.yaml convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak-tcp
  name: keycloak-tcp
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8443"
      port: 8443
      targetPort: 8080
  selector:
    io.kompose.service: keycloak
  type: LoadBalancer
status:
  loadBalancer: {}
