apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.yaml convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-executor
  name: mongodb-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-executor
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../docker-compose.yaml convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-executor
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: executordb
            - name: MONGO_INITDB_PWD
              value: mongopasswd
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_USER
              value: mongoadmin
            - name: TZ
              value: Europe/Madrid
          image: mongo:4.4
          name: mongodb-executor
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongoexecutor-data-4
            - mountPath: /docker-entrypoint-initdb.d/
              name: mongodb-executor-claim1
      hostname: mongodb-executor
      restartPolicy: Always
      volumes:
        - name: mongoexecutor-data-4
          persistentVolumeClaim:
            claimName: mongoexecutor-data-4
        - name: mongodb-executor-claim1
          persistentVolumeClaim:
            claimName: mongodb-executor-claim1
status: {}
