apiVersion: v1
kind: Service
metadata:  
  labels:
    app.kubernetes.io/name: {{ .Values.services.minio.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
  name: {{ .Values.services.minio.name }}
spec:
  type: {{ .Values.services.minio.type }}
  ports:
    - name: "s3"
      port: {{ .Values.services.minio.port }}
      targetPort: {{ .Values.services.minio.port }}
      protocol: {{ .Values.services.minio.protocol }}
    - name: "console"
      port: 9001
      targetPort: 9001
  selector:
    app.kubernetes.io/name: {{ .Values.services.minio.name }}
status:
  loadBalancer: {}
