apiVersion: apps/v1
kind: Deployment
metadata:    
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: {{ .Chart.Name }}    
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
    app.openshift.io/runtime: redis
    app.kubernetes.io/component: database
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  strategy:
    type: Recreate
  template:
    metadata:      
      labels:
        app.kubernetes.io/name: redis
    spec:
      containers:
        - image: {{ .Values.images.redis.name}}:{{ .Values.images.redis.tag }}
          name: redis
          ports:
            - containerPort: {{ .Values.services.redis.port }}
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: cache
      hostname: redis
      restartPolicy: Always
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: cache
status: {}
