apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/part-of: {{ .Chart.Name }}    
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: helm
    app.openshift.io/runtime: zookeeper
    app.kubernetes.io/component: database
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zookeeper
  strategy:
    type: Recreate
  template:
    metadata:      
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: zookeeper
    spec:
      containers:
        - env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          image: {{ .Values.images.zookeeper.name}}:{{ .Values.images.zookeeper.tag }}
          name: zookeeper
          ports:
            - containerPort: {{ .Values.services.zookeeper.port }}
          resources: {}
          volumeMounts:
            - mountPath: /bitnami
              name: zookeeper-data
      restartPolicy: Always
      volumes:
        - name: zookeeper-data
          persistentVolumeClaim:
            claimName: zookeeper-data
status: {}
