project:
  name: ccproject
  domain: apps.ocp4.masales.cloud

# Images
images:  
  observer:
    name: quay.io/marcelosales/observer
    tag: 0.0.6
  injector:
    name: quay.io/marcelosales/injector
    tag: 0.0.6
  api:
    name: quay.io/marcelosales/api
    tag: 0.0.7
  api_app:
    name: quay.io/marcelosales/api-app
    tag: 0.0.6
  executor:
    name: quay.io/marcelosales/executor
    tag: 0.0.6

# Services
services:  
  injector:
    name: injector
    type: ClusterIP
    port: 8080
    protocol: TCP
  api:
    name: api
    type: ClusterIP
    port: 8080
    protocol: TCP    
  api_app:
    name: api-app
    type: ClusterIP
    port: 80
    protocol: TCP

# Secrets
secrets:  
  injector:
    name: injector-secret
    injector_newsdata_apikey: pub_146789360c2a1420986503a543273fbf22306
    injector_newsapi_apikey: 3911bdc960ab4abfb3efb9630ab25188
    injector_mediastack_apikey: 5d1a42a53fbaedc4e46d62157bec1f16

  api:
    name: api-secret
    api_keycloak_client_id: api-backend
    api_keycloak_client_secret: jIjvenRCzr0x0ccV6WDjDbh22NBluhPf
  
  executor:
    name: executor-secret

    
# ConfigMaps
configmaps:
  observer:
    name: observer-config
    observer_metrics_schedule: "30s"
  
  injector:
    name: injector-config
    injector_newsdata_url: https://newsdata.io/api/1
    injector_newsapi_url: https://newsapi.org/v2
    injector_mediastack_url: http://api.mediastack.com/v1
    injector_cron: "0 * * * * ?"
    injector_skip_schedule: false

  api:
    name: api-config
  
  api_app:
    name: api-app-config
    port: 80
  
  executor:
    name: executor-config

route:
  api:
    name: api-route
    host: http://api-ccproject.apps.ocp4.masales.cloud/    
  api_app:
    name: api-app-route
    host: http://api-app-ccproject.apps.ocp4.masales.cloud/