apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.service.expose: "true"
    kompose.service.type: LoadBalancer
  creationTimestamp: null
  labels:
    io.kompose.service: injector
  name: injector
spec:
  replicas: 1
  selector:
    io.kompose.service: injector
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: injector
    spec:
      containers:
        - env:
            - name: INJECTOR_CRON
            - name: INJECTOR_DB_HOST
            - name: INJECTOR_DB_NAME
            - name: INJECTOR_DB_PASSWORD
            - name: INJECTOR_DB_PORT
            - name: INJECTOR_DB_USER
            - name: INJECTOR_HTTP_PORT
            - name: INJECTOR_MEDIASTACK_APIKEY
            - name: INJECTOR_MEDIASTACK_URL
            - name: INJECTOR_NEWSAPI_APIKEY
            - name: INJECTOR_NEWSAPI_URL
            - name: INJECTOR_NEWSDATA_APIKEY
            - name: INJECTOR_NEWSDATA_URL
            - name: KAFKA_SERVERS
            - name: MINIO_ENDPOINT
            - name: MINIO_ROOT_PASSWORD
            - name: MINIO_ROOT_USER
            - name: REDIS_ENDPOINT
            - name: REDIS_PASSWORD
            - name: TZ
              value: Europe/Madrid
          image: ' '
          name: injector
          ports:
            - containerPort: 8080
          resources: {}
      hostname: injector
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - injector
        from:
          kind: ImageStreamTag
          name: injector:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
