apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker.io/bitnami/kafka:3.3
      generation: null
      importPolicy: {}
      name: "3.3"
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
