apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: quay.io/keycloak/keycloak:20.0
      generation: null
      importPolicy: {}
      name: "20.0"
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
