apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-keycloak
  name: postgres-keycloak
spec:
  replicas: 1
  selector:
    io.kompose.service: postgres-keycloak
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgres-keycloak
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: keycloak
            - name: TZ
              value: Europe/Madrid
          image: ' '
          name: postgres-keycloak
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-keycloak-data
      hostname: postgres-keycloak
      restartPolicy: Always
      volumes:
        - name: postgres-keycloak-data
          persistentVolumeClaim:
            claimName: postgres-keycloak-data
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - postgres-keycloak
        from:
          kind: ImageStreamTag
          name: postgres-keycloak:13
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
