apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-api
  name: postgres-api
spec:
  replicas: 1
  selector:
    io.kompose.service: postgres-api
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgres-api
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: apidb
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
            - name: TZ
              value: Europe/Madrid
          image: ' '
          name: postgres-api
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgapi-data
      hostname: postgres-api
      restartPolicy: Always
      volumes:
        - name: pgapi-data
          persistentVolumeClaim:
            claimName: pgapi-data
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - postgres-api
        from:
          kind: ImageStreamTag
          name: postgres-api:13
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
