apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker.io/bitnami/zookeeper:3.8
      generation: null
      importPolicy: {}
      name: "3.8"
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
